#
#  https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/
#
#  kustomize build deployments/dev/training-pipeline | kubectl apply -f -
#
---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mdendpoints
resources:
  - ./mdendpoints-cm.yaml
  - ./mdendpoints-s.yaml
#  - ./mdendpoints-d.yaml
#  - ./mdendpoints-cj.yaml
  - ./mdendpoints-j.yaml
